import { StaticImageData } from "next/image";
import apart1 from "@/public/asset/apart11.jpg"
import apart2 from "@/public/asset/apart12.jpg"
import apart3 from "@/public/asset/apart13.jpg"
import apart4 from "@/public/asset/apart14.jpg"
import apart5 from "@/public/asset/apart15.jpg"
import apart6 from "@/public/asset/apart110.jpg"
import apart7 from "@/public/asset/apart16.jpg"
import apart8 from "@/public/asset/apart17.jpg"
import apart9 from "@/public/asset/apart18.jpg"
import apart10 from "@/public/asset/apart19.jpg"
import apart11 from "@/public/asset/apart110.jpg"
import apart12 from "@/public/asset/apart111.jpg"
import apart13 from "@/public/asset/apart112.jpg"
import apart14 from "@/public/asset/apart113.jpg"
import apart15 from "@/public/asset/apart114.jpg"
import apart16 from "@/public/asset/apart115.jpg"
import apart17 from "@/public/asset/apart116.jpg"


export type PropertyType = "Appartement" | "Maison" | "Studio" | "Immeuble" | "Villa" | "Loft" | "Duplex" | "Penthouse";

export interface Property {
  id: string;
  name: string;
  price: number; // en €
  bedrooms: number;
  bathrooms: number;
  address: string;
  rating: number; // entre 1 et 5
  type: PropertyType;
  features: string[]; // Ex: ["Piscine", "Balcon", "Meublé"]
  area: number; // en m²
  image: StaticImageData; // URL de l’image
  listedAt: string; // Date ISO
  available: boolean;
}


export const properties = [
  {
    id: "prop_1",
    name: "Duplex",
    price: 230339,
    bedrooms: 5,
    bathrooms: 1,
    address: "3, chemin Leblanc",
    rating: 4.4,
    type: "Maison",
    features: ['Vue sur le fleuve', 'Meublé', 'Piscine', 'Climatisation'],
    area: 159,
    image: apart1,
    listedAt: "2025-06-02",
    available: false
  },
  {
    id: "prop_2",
    name: " Collin-sur-Mer",
    price: 182487,
    bedrooms: 2,
    bathrooms: 3,
    address: " 14701 Parent-sur-Mer",
    rating: 4.7,
    type: "Villa",
    features: ['Buanderie', 'Cuisine extérieure', 'Vue sur le fleuve'],
    area: 44,
    image: apart2,
    listedAt: "2025-07-13",
    available: true
  },
  {
    id: "prop_3",
    name: "Penthouse",
    price: 210127,
    bedrooms: 4,
    bathrooms: 1,
    address: " 30274 Sainte Susannenec",
    rating: 4.5,
    type: "Appartement",
    features: ['Meublé', 'Domotique', 'Générateur'],
    area: 554,
    image: apart3,
    listedAt: "2025-07-13",
    available: true
  },
  {
    id: "prop_4",
    name: "Penthouse",
    price: 207954,
    bedrooms: 4,
    bathrooms: 2,
    address: "82, rue de Dupuis",
    rating: 3.9,
    type: "Duplex",
    features: ['Garage', 'Climatisation', 'Domotique', 'Meublé', 'Ascenseur', 'Internet inclus'],
    area: 256,
    image: apart4,
    listedAt: "2025-05-29",
    available: false
  },
  {
    id: "prop_5",
    name: " Voisinboeuf",
    price: 260547,
    bedrooms: 2,
    bathrooms: 1,
    address: "6, rue de Delorme",
    rating: 4.9,
    type: "Penthouse",
    features: ['Générateur', 'Garage', 'Sécurité 24/7', 'Salle de jeux'],
    area: 460,
    image:apart5,
    listedAt: "2025-07-15",
    available: true
  },
  {
    id: "prop_6",
    name: "Penthouse à Lopez",
    price: 283545,
    bedrooms: 3,
    bathrooms: 4,
    address: "64, rue Chauvin",
    rating: 4.1,
    type: "Maison",
    features: ['Domotique', 'Meublé', 'Générateur', 'Vue sur ville', 'Ascenseur'],
    area: 59,
    image: apart6,
    listedAt: "2025-06-01",
    available: false
  },
  {
    id: "prop_7",
    name: "Brunel-sur-Mer",
    price: 244757,
    bedrooms: 6,
    bathrooms: 4,
    address: " 82063 Sainte Océanenec",
    rating: 4.9,
    type: "Villa",
    features: ['Piscine', 'Jardin', 'Salle de sport'],
    area: 116,
    image: apart7,
    listedAt: "2025-06-27",
    available: true
  },
  {
    id: "prop_8",
    name: " Jacquesdan",
    price: 160565,
    bedrooms: 1,
    bathrooms: 4,
    address: " 22802 Guyon",
    rating: 4.4,
    type: "Immeuble",
    features: ['Sécurité 24/7', 'Cuisine extérieure', 'Internet inclus', 'Générateur'],
    area: 375,
    image: apart8,
    listedAt: "2025-06-29",
    available: false
  },
  {
    id: "prop_9",
    name: "Penthouse ",
    price: 266179,
    bedrooms: 2,
    bathrooms: 4,
    address: "4, avenue Le Roux",
    rating: 3.9,
    type: "Villa",
    features: ['Sécurité 24/7', 'Vue sur le fleuve', 'Salle de sport', 'Piscine', 'Ascenseur', 'Climatisation'],
    area: 332,
    image: apart9,
    listedAt: "2025-07-02",
    available: true
  },
  {
    id: "prop_10",
    name: "Duplex ",
    price: 95431,
    bedrooms: 6,
    bathrooms: 4,
    address: " 40256 Bernardboeuf",
    rating: 4.7,
    type: "Maison",
    features: ['Buanderie', 'Balcon', 'Cuisine extérieure', 'Générateur'],
    area: 552,
    image: apart10,
    listedAt: "2025-06-25",
    available: false
  },
  {
    id: "prop_11",
    name: " Salmon",
    price: 52014,
    bedrooms: 4,
    bathrooms: 3,
    address: " 73552 Saint Camille",
    rating: 4.1,
    type: "Duplex",
    features: ['Salle de jeux', 'Vue sur le fleuve', 'Cuisine extérieure'],
    area: 147,
    image: apart11,
    listedAt: "2025-06-10",
    available: true
  },
  {
    id: "prop_12",
    name: "Lefebvre Deschamps",
    price: 293198,
    bedrooms: 2,
    bathrooms: 4,
    address: ", 60407 Fouquet",
    rating: 4.9,
    type: "Penthouse",
    features: ['Ascenseur', 'Buanderie', 'Salle de jeux', 'Climatisation', 'Salle de sport', 'Cuisine extérieure'],
    area: 538,
    image: apart12,
    listedAt: "2025-06-04",
    available: false
  },
  {
    id: "prop_13",
    name: "Boyer-sur-Gay",
    price: 87096,
    bedrooms: 2,
    bathrooms: 1,
    address: "8, rue Odette Diaz",
    rating: 3.5,
    type: "Studio",
    features: ['Climatisation', 'Terrasse', 'Salle de jeux', 'Balcon', 'Jardin', 'Salle de sport'],
    area: 107,
    image: apart13,
    listedAt: "2025-06-17",
    available: true
  },
  {
    id: "prop_14",
    name: "Launay-les-Bains",
    price: 78300,
    bedrooms: 1,
    bathrooms: 1,
    address: "41893  Patrick-Mer",
    rating: 4.5,
    type: "Appartement",
    features: ['Meublé', 'Ascenseur', 'Sécurité 24/7', 'Piscine', 'Salle de jeux', 'Vue sur le fleuve'],
    area: 185,
    image: apart14,
    listedAt: "2025-06-29",
    available: true
  },
  {
    id: "prop_15",
    name: " Rivière",
    price: 194491,
    bedrooms: 2,
    bathrooms: 4,
    address: " 46868 Marion",
    rating: 4.2,
    type: "Immeuble",
    features: ['Piscine', 'Domotique', 'Sécurité 24/7', 'Vue sur le fleuve'],
    area: 40,
    image: apart15,
    listedAt: "2025-07-16",
    available: true
  },
  {
    id: "prop_16",
    name: "Penthouse à Lenoir",
    price: 46980,
    bedrooms: 2,
    bathrooms: 2,
    address: "89869 Aubert",
    rating: 4.5,
    type: "Immeuble",
    features: ['Domotique', 'Terrasse', 'Cuisine extérieure', 'Vue sur ville', 'Salle de jeux'],
    area: 268,
    image: apart16,
    listedAt: "2025-06-22",
    available: false
  },
  {
    id: "prop_17",
    name: "Tanguydan",
    price: 282743,
    bedrooms: 6,
    bathrooms: 1,
    address: " 29276 Martins",
    rating: 3.5,
    type: "Immeuble",
    features: ['Cuisine extérieure', 'Vue sur ville', 'Internet inclus'],
    area: 311,
    image: apart17,
    listedAt: "2025-07-18",
    available: false
  },
  {
    id: "prop_18",
    name: "costa",
    price: 113517,
    bedrooms: 3,
    bathrooms: 2,
    address: "51404 Saint Arthur",
    rating: 4.0,
    type: "Studio",
    features: ['Garage', 'Buanderie', 'Terrasse', 'Générateur'],
    area: 334,
    image: apart1,
    listedAt: "2025-05-27",
    available: false
  },
  {
    id: "prop_19",
    name: "Bazin-Maillet",
    price: 143154,
    bedrooms: 4,
    bathrooms: 1,
    address: " 07431 Neveu",
    rating: 4.5,
    type: "Studio",
    features: ['Salle de jeux', 'Salle de sport', 'Buanderie', 'Ascenseur'],
    area: 559,
    image: apart2,
    listedAt: "2025-07-01",
    available: false
  },
  {
    id: "prop_20",
    name: "GodardBourg",
    price: 269429,
    bedrooms: 3,
    bathrooms: 4,
    address: "17240 Chrétien",
    rating: 4.1,
    type: "Penthouse",
    features: ['Vue sur ville', 'Vue sur le fleuve', 'Terrasse', 'Garage'],
    area: 347,
    image: apart3,
    listedAt: "2025-06-27",
    available: false
  },
  {
    id: "prop_21",
    name: " Sainte David",
    price: 229160,
    bedrooms: 5,
    bathrooms: 1,
    address: " 56325 Dubois",
    rating: 4.5,
    type: "Duplex",
    features: ['Climatisation', 'Jardin', 'Internet inclus', 'Vue sur le fleuve'],
    area: 69,
    image: apart4,
    listedAt: "2025-06-29",
    available: false
  },
  {
    id: "prop_22",
    name: " Lebon",
    price: 248159,
    bedrooms: 4,
    bathrooms: 2,
    address: "42688 Traore",
    rating: 4.7,
    type: "Penthouse",
    features: ['Garage', 'Salle de sport', 'Ascenseur', 'Climatisation', 'Balcon'],
    area: 400,
    image: apart5,
    listedAt: "2025-07-23",
    available: false
  },
  {
    id: "prop_23",
    name: " Saint Étienne",
    price: 75632,
    bedrooms: 3,
    bathrooms: 1,
    address: "3, chemin Legros",
    rating: 3.9,
    type: "Maison",
    features: ['Salle de sport', 'Piscine', 'Balcon', 'Climatisation', 'Domotique'],
    area: 587,
    image:apart6,
    listedAt: "2025-05-27",
    available: false
  },
  {
    id: "prop_24",
    name: "Studio à Giraud",
    price: 47418,
    bedrooms: 1,
    bathrooms: 3,
    address: " 95627 Sainte Margotnec",
    rating: 3.8,
    type: "Studio",
    features: ['Domotique', 'Meublé', 'Balcon', 'Jardin', 'Terrasse'],
    area: 500,
    image:apart7,
    listedAt: "2025-06-02",
    available: false
  },
  {
    id: "prop_25",
    name: " DelannoyBourg",
    price: 92389,
    bedrooms: 2,
    bathrooms: 1,
    address: " 32044 Sainte Pénélope",
    rating: 4.4,
    type: "Maison",
    features: ['Internet inclus', 'Balcon', 'Salle de jeux', 'Jardin', 'Vue sur le fleuve'],
    area: 298,
    image: apart8,
    listedAt: "2025-07-19",
    available: true
  },
  {
    id: "prop_26",
    name: " Prévostdan",
    price: 207189,
    bedrooms: 2,
    bathrooms: 1,
    address: " 73467 NavarroVille",
    rating: 4.8,
    type: "Villa",
    features: ['Vue sur le fleuve', 'Salle de jeux', 'Sécurité 24/7', 'Salle de sport', 'Générateur', 'Garage'],
    area: 535,
    image:apart9,
    listedAt: "2025-05-28",
    available: true
  },
  {
    id: "prop_27",
    name: " Lacombe",
    price: 154682,
    bedrooms: 6,
    bathrooms: 1,
    address: " 23604 Parentboeuf",
    rating: 4.2,
    type: "Villa",
    features: ['Jardin', 'Balcon', 'Meublé', 'Vue sur ville'],
    area: 366,
    image: apart10,
    listedAt: "2025-07-23",
    available: false
  },
  {
    id: "prop_28",
    name: "Rousset",
    price: 196046,
    bedrooms: 2,
    bathrooms: 4,
    address: "62, rue Gérard",
    rating: 4.4,
    type: "Maison",
    features: ['Sécurité 24/7', 'Terrasse', 'Balcon', 'Ascenseur', 'Buanderie'],
    area: 386,
    image: apart11,
    listedAt: "2025-05-29",
    available: false
  },
  {
    id: "prop_29",
    name: "Descamps",
    price: 250248,
    bedrooms: 6,
    bathrooms: 4,
    address: "63276 Seguin",
    rating: 3.9,
    type: "Maison",
    features: ['Cuisine extérieure', 'Sécurité 24/7', 'Salle de jeux', 'Garage', 'Vue sur ville'],
    area: 434,
    image: apart12,
    listedAt: "2025-06-25",
    available: false
  },
  {
    id: "prop_30",
    name: " Sainte Claire",
    price: 214959,
    bedrooms: 3,
    bathrooms: 4,
    address: "70865 Letellier",
    rating: 4.3,
    type: "Villa",
    features: ['Climatisation', 'Internet inclus', 'Générateur'],
    area: 435,
    image: apart13,
    listedAt: "2025-05-30",
    available: true
  },
  {
    id: "prop_31",
    name: "Pruvost-Courtois",
    price: 240059,
    bedrooms: 3,
    bathrooms: 1,
    address: "41825 Delaunay",
    rating: 3.6,
    type: "Studio",
    features: ['Vue sur le fleuve', 'Buanderie', 'Piscine', 'Cuisine extérieure', 'Sécurité 24/7'],
    area: 578,
    image: apart14,
    listedAt: "2025-07-11",
    available: true
  },
  {
    id: "prop_32",
    name: " Didier",
    price: 64155,
    bedrooms: 6,
    bathrooms: 3,
    address: " 46355 Fourniernec",
    rating: 4.1,
    type: "Penthouse",
    features: ['Domotique', 'Ascenseur', 'Terrasse', 'Buanderie', 'Internet inclus'],
    area: 344,
    image: apart15,
    listedAt: "2025-05-29",
    available: true
  },
  {
    id: "prop_33",
    name: " Gomes",
    price: 77533,
    bedrooms: 2,
    bathrooms: 2,
    address: " 53885 Saint Michèle",
    rating: 3.6,
    type: "Appartement",
    features: ['Balcon', 'Salle de sport', 'Internet inclus', 'Salle de jeux'],
    area: 205,
    image: apart16,
    listedAt: "2025-06-19",
    available: false
  },
  {
    id: "prop_34",
    name: "Constancedan",
    price: 247721,
    bedrooms: 3,
    bathrooms: 3,
    address: " 80182 Bourdon",
    rating: 3.6,
    type: "Duplex",
    features: ['Garage', 'Salle de jeux', 'Piscine'],
    area: 115,
    image: apart17,
    listedAt: "2025-07-08",
    available: false
  },
  {
    id: "prop_35",
    name: " Lambert",
    price: 236043,
    bedrooms: 3,
    bathrooms: 4,
    address: " 82660 Martyboeuf",
    rating: 3.8,
    type: "Immeuble",
    features: ['Buanderie', 'Jardin', 'Générateur'],
    area: 219,
    image: apart1,
    listedAt: "2025-07-10",
    available: false
  },
  {
    id: "prop_36",
    name: " Rolland",
    price: 74665,
    bedrooms: 5,
    bathrooms: 2,
    address: " 08352 Lecoq-sur-Guibert",
    rating: 4.4,
    type: "Duplex",
    features: ['Climatisation', 'Buanderie', 'Cuisine extérieure', 'Vue sur ville', 'Meublé'],
    area: 179,
    image: apart2,
    listedAt: "2025-07-16",
    available: false
  },
  {
    id: "prop_37",
    name: "Saint Théophile",
    price: 287226,
    bedrooms: 3,
    bathrooms: 2,
    address: " 57357 Gaudin",
    rating: 4.8,
    type: "Immeuble",
    features: ['Salle de sport', 'Vue sur ville', 'Salle de jeux', 'Internet inclus'],
    area: 596,
    image:apart3,
    listedAt: "2025-05-27",
    available: true
  },
  {
    id: "prop_38",
    name: " Chauvin",
    price: 256249,
    bedrooms: 3,
    bathrooms: 3,
    address: " 84832 Munoz-les-Bains",
    rating: 4.5,
    type: "Maison",
    features: ['Ascenseur', 'Garage', 'Vue sur ville', 'Buanderie'],
    area: 363,
    image: apart4,
    listedAt: "2025-06-20",
    available: false
  },
  {
    id: "prop_39",
    name: "Hamon-Forêt",
    price: 108538,
    bedrooms: 5,
    bathrooms: 3,
    address: "31446 Lebrun-sur-Mer",
    rating: 4.4,
    type: "Immeuble",
    features: ['Salle de jeux', 'Piscine', 'Balcon', 'Salle de sport', 'Buanderie', 'Sécurité 24/7'],
    area: 53,
    image: apart5,
    listedAt: "2025-05-31",
    available: false
  },
  {
    id: "prop_40",
    name: " Pascal-Gimenez",
    price: 178760,
    bedrooms: 2,
    bathrooms: 3,
    address: " 13818 Peron",
    rating: 3.5,
    type: "Appartement",
    features: ['Meublé', 'Climatisation', 'Garage'],
    area: 547,
    image: apart6,
    listedAt: "2025-05-26",
    available: false
  },
  {
    id: "prop_41",
    name: " Olivier",
    price: 111334,
    bedrooms: 4,
    bathrooms: 1,
    address: " 61337 Boucher",
    rating: 4.1,
    type: "Studio",
    features: ['Salle de jeux', 'Piscine', 'Vue sur le fleuve', 'Salle de sport', 'Buanderie'],
    area: 346,
    image: apart7,
    listedAt: "2025-05-27",
    available: true
  },
  {
    id: "prop_42",
    name: " Guérin-les-Bains",
    price: 89968,
    bedrooms: 2,
    bathrooms: 1,
    address: " 19177 LabbéBourg",
    rating: 3.8,
    type: "Appartement",
    features: ['Vue sur le fleuve', 'Vue sur ville', 'Sécurité 24/7', 'Jardin', 'Buanderie', 'Ascenseur'],
    area: 397,
    image: apart8,
    listedAt: "2025-06-03",
    available: false
  },
  {
    id: "prop_43",
    name: "Breton",
    price: 289054,
    bedrooms: 2,
    bathrooms: 4,
    address: " 08987 Marchal",
    rating: 4.1,
    type: "Duplex",
    features: ['Domotique', 'Piscine', 'Générateur', 'Salle de jeux', 'Cuisine extérieure', 'Salle de sport'],
    area: 499,
    image: apart9,
    listedAt: "2025-06-17",
    available: true
  },
  {
    id: "prop_44",
    name: "BesnardBourg",
    price: 290501,
    bedrooms: 4,
    bathrooms: 4,
    address: " 71107 Delaunay-sur-Ferreira",
    rating: 3.8,
    type: "Maison",
    features: ['Sécurité 24/7', 'Jardin', 'Salle de jeux'],
    area: 176,
    image: apart10,
    listedAt: "2025-07-11",
    available: false
  },
  {
    id: "prop_45",
    name: "Maison à Delattre",
    price: 226740,
    bedrooms: 5,
    bathrooms: 2,
    address: " 81133 Saint GabrielVille",
    rating: 3.8,
    type: "Immeuble",
    features: ['Climatisation', 'Garage', 'Balcon', 'Buanderie', 'Vue sur le fleuve', 'Jardin'],
    area: 588,
    image: apart11,
    listedAt: "2025-06-09",
    available: false
  },
  {
    id: "prop_46",
    name: "Sainte Danieldan",
    price: 215325,
    bedrooms: 5,
    bathrooms: 2,
    address: "28802 Noël",
    rating: 4.1,
    type: "Penthouse",
    features: ['Balcon', 'Ascenseur', 'Jardin', 'Cuisine extérieure'],
    area: 586,
    image: apart12,
    listedAt: "2025-05-27",
    available: false
  },
  {
    id: "prop_47",
    name: "Faivre-sur-Duval",
    price: 195661,
    bedrooms: 4,
    bathrooms: 3,
    address: "85661 Sainte Jacqueline",
    rating: 4.7,
    type: "Immeuble",
    features: ['Garage', 'Domotique', 'Buanderie', 'Salle de sport', 'Générateur', 'Meublé'],
    area: 369,
    image: apart13,
    listedAt: "2025-07-01",
    available: true
  },
  {
    id: "prop_48",
    name: "Lecomte-Chevallier",
    price: 178227,
    bedrooms: 2,
    bathrooms: 2,
    address: "98121 Saint André-la-Forêt",
    rating: 3.7,
    type: "Villa",
    features: ['Balcon', 'Vue sur ville', 'Buanderie', 'Cuisine extérieure', 'Domotique', 'Salle de sport'],
    area: 586,
    image: apart14,
    listedAt: "2025-06-12",
    available: false
  },
  {
    id: "prop_49",
    name: "Villa à Gonzalez",
    price: 183801,
    bedrooms: 3,
    bathrooms: 4,
    address: "38466 Hoarau-sur-Antoine",
    rating: 4.2,
    type: "Studio",
    features: ['Salle de jeux', 'Internet inclus', 'Buanderie'],
    area: 547,
    image: apart15,
    listedAt: "2025-07-07",
    available: true
  },
  {
    id: "prop_50",
    name: "Bouvet-la-Forêt",
    price: 215876,
    bedrooms: 2,
    bathrooms: 3,
    address: "79546 Traore",
    rating: 3.8,
    type: "Immeuble",
    features: ['Balcon', 'Sécurité 24/7', 'Générateur', 'Garage'],
    area: 478,
    image: apart16,
    listedAt: "2025-06-19",
    available: false
  },
] as Property[]